### PR TITLE
DependencyResolver / DependencyResolverProxy alias #128

### PR DESCRIPTION
**Pull request by MontakOleg**
Hello!
Just implemented https://github.com/scribd/Weaver/issues/128

### CODE REVIEW

**Comment by trupin** [comment]
Thank you @MontakOleg,

I will do some testing and merge if I don't find any issue.

**Comment by trupin** [comment]
Hi @MontakOleg,

After trying it out, it looks like your changes make Weaver create an extra `typealias` for every type, which is a lot of added boilerplate code.

Since we're trying to solve a scenario which maybe happens ~5% of the time, I think we should find a way to solve this by only impacting the `Proxy` structs and not the rest of the code. It looks like a more scalable solution to me. 

I'm thinking that a better solution to this problem could be to rename the concerned dependency resolvers only to `AInternalDependencyResolver` and rename their proxy struct to `ADependencyResolver`. It would scale better this way.

We could even go further by having the proxy structs implementing the internal dependency resolver. It would allow us to make the `value` attribute private and hide the proxy aspect entirely to developers.

**Comment by trupin** [comment]
Here is an example of what I'm talking about above.

```swift
protocol AInternalDependencyResolver {
    var anAmbiguousDependency_ad0737d39be39483b642e7dbfef913a379412836: String { get }
}

typealias ADependencyResolver = ADependencyResolverProxy

struct ADependencyResolverProxy {

    let value: AInternalDependencyResolver

    init(_ value: AInternalDependencyResolver) { self.value = value }

    var anAmbiguousDependency: String {
        return value.anAmbiguousDependency_ad0737d39be39483b642e7dbfef913a379412836
    }
}
```

**Comment by MontakOleg** [comment]
Hi @trupin, 

Got it.
Can't fix this right now, will look at this closer a bit later.

**Comment by MontakOleg** [comment]
@trupin done, please look at this

**Comment by strawb3rryx7** [comment]
@trupin This situation should be indicated in the README to avoid confusion until the issue being solved. I thought to use `DependencyTypeDependencyResolverProxy` as a workaround by exploring the generated code file. It can be challenging for new Weaver users.

**Comment by trupin** [comment]
Thanks for these changes @MontakOleg.

**Pull request merged**
